project_id = "yzrrlxnnqwihkkmokrso"

[functions.get-onesignal-config]
verify_jwt = true

[functions.send-onesignal-push]
verify_jwt = true

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.delete-account]
verify_jwt = true
